#!/bin/bash

count=0

mails="$(curl -u "txc.yang@gmail.com":"pass" --silent "https://mail.google.com/mail/feed/atom"
)"

if [ -z "$mails" ]
then
notify-send "Mails Check Error"
exit 1
fi

mails="$(echo "$mails" | egrep 'fullcount|title' \
|sed -e '2,$s/.*<fullcount>//' -e '2,$s/<\/fullcount>//' \
-e '2,$s/.*<title>//' -e '2,$s/<\/title>//' |sed -n '2,$p' )"

count="$(echo "$mails" | sed -n '1p')"
mails="$(echo "$mails" | sed -e '2,$s/^/\* /' | sed -n '2,$p')"

if [ "$count" -gt "0" ]
then
notify-send "Get $count new mails" "$mails"
fi

exit 0
